language: cpp

sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get --no-install-recommends install latexmk texlive-latex3 texlive-latex-recommended texlive-latex-extra texlive-fonts-extra cmake octave octave-odepkg

script:
  - mkdir build && cd build && cmake .. && make -j32
